# Generated by Django 2.2.4 on 2019-10-31 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('valortexto', models.CharField(max_length=100)),
                ('valorinteger', models.IntegerField()),
                ('valordecimal', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('valorfecha', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha Creacion')),
                ('android_id', models.IntegerField(blank=True, default=0, null=True)),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('montoabona', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('nro', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('montodescuento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cantidaddescuento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('enviodomicilio', models.BooleanField(default=False, verbose_name='¿Envio a Domicilio?')),
                ('visto', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('tiempodemora', models.CharField(default=False, max_length=10, verbose_name='Tiempo Demora')),
                ('horarecepcion', models.TimeField(blank=True, default=0, null=True, verbose_name='Hora Recepcion')),
                ('horaentrega', models.TimeField(default=0, verbose_name='Hora Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('preciounitario', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('codigoexterno', models.CharField(blank=True, max_length=50, verbose_name='Codigo Externo')),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True, verbose_name='¿Producto En Venta?')),
                ('ispromo', models.BooleanField(default=False, verbose_name='¿En Promocion?')),
                ('preciopromo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unidadmedida', models.IntegerField(default=1, verbose_name='Unidad de Medida')),
                ('isfraccionado', models.BooleanField(default=False, verbose_name='¿Es Fraccionado?')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='description',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='name',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('enabled', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('preciopromo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('importedescuento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('precioanterior', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fechadesde', models.DateTimeField(verbose_name='Fecha Hasta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Marca'),
        ),
        migrations.CreateModel(
            name='Pedidodetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Producto')),
            ],
        ),
    ]
