# Generated by Django 2.2.4 on 2019-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20191030_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('serie', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.IntegerField()),
            ],
        ),
    ]
